<section>
    <article>
        <h2><?php echo htmlspecialchars($article['title']); ?></h2>
        <small><?=htmlspecialchars($article['label'])?></small>
        <p><?= (new DateTime($article['created_at']))->format('d/m/Y'); ?></p>
        <img src="<?=htmlspecialchars($article['image']);?>" alt="">
        <div><?= htmlspecialchars($article['content']); ?></div>
    </article>
</section>

<section>

    <!-- Affichage des messages d'erreur le cas échéant --> 
    <?php if (isset($errors) && !empty($errors)): ?>
        <?php foreach ($errors as $error): ?>
            <p><?=$error;?></p>
        <?php endforeach; ?>
    <?php endif; ?>

    <!-- Si l'utilisateur est connecté, on affiche le formulaire d'ajout de commentaire -->
    <?php if ((new \App\Framework\UserSession())->isAuthenticated()): ?>

        <!-- Formulaire d'ajout de commentaire --> 
        <form action="<?=url('/article', ['article_id' => $article['id_article']]);?>" method="POST">
            <fieldset>
                <legend>Ajouter un commentaire</legend>
                <div>
                    <label for="content">Commentaire</label>
                    <textarea id="content" name="content"></textarea>
                </div>
                <input type="submit" value="Valider">
            </fieldset>
        </form>

    <?php else: ?>
        <p>Pour poster un commentaire, 
        <a href="<?=url('/login');?>">connectez-vous</a> 
        ou <a href="<?=url('/signup');?>">créez un compte !</a></p>
    <?php endif; ?>

    <h2>Commentaires</h2>
    <?php if ($comments): ?>
        <ul> 
            <?php foreach ($comments as $comment):?>
                <li>
                    <h3>Ajouté par <?=htmlspecialchars($comment['firstname'] . ' ' . $comment['lastname'])?> le <?= (new DateTime($comment['created_at']))->format('d/m/Y à H\hi '); ?></h3>
                    <p><?=htmlspecialchars($comment['content']);?></p>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</section>