<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon blog</title>
    <link rel="stylesheet" href="<?=asset('css/style.css');?>">
</head>
<body>
    <header>
        <h1><a href="<?=url('/');?>">Mon blog</a></h1>
        <nav>
            <!-- Affichage dans le menu de la liste des catégories -->
            <?php foreach ((new \App\Model\CategoryModel)->getAllCategories() as $category): ?>
                <a href="/category?category_id=<?=$category['id_category'];?>"><?=$category['label'];?></a>
            <?php endforeach; ?>

            <!-- Si l'utilisateur n'est PAS connecté -->  
            <?php if (!isAuthenticated()): ?>
                <a href="<?=url('/signup');?>">Créer un compte</a>
                <a href="<?=url('/login');?>">Connexion</a>
            <!-- Sinon (si l'utilisateur est connecté) -->
            <?php else: ?>
                <a href="<?=url('/logout');?>">Déconnexion</a>
            <?php endif; ?>
        </nav>
    </header>
    <main>
        <!-- Affichage des messaghes flash -->
         <?php if (hasFlash()): ?>
            <?php foreach (getFlash() as $message): ?>
                <p><?=$message;?></p>
            <?php endforeach; ?>
         <?php endif; ?>

        <?php require '../templates/'.$template.'.phtml'; ?>
    </main>
</body>
</html>