<section>
    <h2>Nos derniers articles</h2>
    <?php foreach ($articles as $article): ?>
        <article>
            <h3><?php echo $article['title']; ?></h3>
            <p><?= (new DateTime($article['created_at']))->format('d/m/Y'); ?></p>
            <div><?= mb_substr($article['content'], 0, 150); ?> [...]</div>
            <a href="/article?article_id=<?=$article['id_article'];?>">Lire la suite</a>
        </article>
    <?php endforeach; ?>
</section>
    