<?php foreach ($articles as $article): ?>
    <article>
        <h3><?php echo htmlspecialchars($article['title']); ?></h3>
        <small><?=htmlspecialchars($article['label'])?></small>
        <p><?= (new DateTime($article['created_at']))->format('d/m/Y'); ?></p>
        <img src="<?=htmlspecialchars($article['image']);?>" alt="">
        <div><?= htmlspecialchars(mb_substr($article['content'], 0, 150)); ?> [...]</div>
        <a href="<?=url('/article', ['article_id' => intval($article['id_article'])]);?>">Lire la suite</a>
    </article>
<?php endforeach; ?>